# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: my_service.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10my_service.proto\x12\nmy_service\"\x1d\n\x0bPingRequest\x12\x0e\n\x06number\x18\x01 \x01(\x03\"\x1e\n\x0cPingResponse\x12\x0e\n\x06number\x18\x01 \x01(\x03\x32R\n\tMyService\x12\x45\n\nPingStream\x12\x17.my_service.PingRequest\x1a\x18.my_service.PingResponse\"\x00(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'my_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PINGREQUEST']._serialized_start=32
  _globals['_PINGREQUEST']._serialized_end=61
  _globals['_PINGRESPONSE']._serialized_start=63
  _globals['_PINGRESPONSE']._serialized_end=93
  _globals['_MYSERVICE']._serialized_start=95
  _globals['_MYSERVICE']._serialized_end=177
# @@protoc_insertion_point(module_scope)
